#DB Configuration
spring:
  datasource: 
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xiaot
    username: root
    password: root
    
server :
  port : 6060

mybatis:
  configuration:
    map-underscore-to-camel-case: true